language: go
go:
 - 1.2
 - 1.3
 - 1.4
 - 1.5
 - release
  - tip

install:
  - go get -v github.com/onsi/ginkgo/ginkgo
  - go get github.com/stretchr/testify/assert
  - export PATH=$PATH:$HOME/gopath/bin

script:
 - make test
